nginx for rsiviz
radiasoft/rsconf pull request #195
Opened 2022-05-05 16:59 UTC by e-carlin

2022-05-05 19:55 UTC, robnagler requested changes

2022-05-06 15:09 UTC, e-carlin commented on rsconf/package_data/rsiviz/nginx.conf.jinja
> +    location /kpmcyjtsoxks/ {
doh, thanks b04db4b

2022-05-06 15:09 UTC, e-carlin commented on rsconf/package_data/rsiviz/nginx.conf.jinja
> +}
b04db4b

2022-05-06 15:42 UTC, merged

2022-05-06 15:42 UTC, e-carlin commented
Merging in order to keep moving but please review and i will fix up

2022-05-06 15:58 UTC, robnagler commented on rsconf/package_data/rsiviz/nginx.conf.jinja
> +client_max_body_size 200m;
Probably needs to be larger. May want it configurable.

2022-05-06 15:58 UTC, robnagler commented on rsconf/package_data/rsiviz/nginx.conf.jinja
> +    server_name {{ nginx.vhost }};
Terminate with TLS (see sirepo). You can use a *.radiasoft.org service name.

2022-05-06 15:58 UTC, robnagler commented on rsconf/package_data/rsiviz/nginx.conf.jinja
> +    location /{{ rsiviz.url_secret }}/ {
You can remove this, and instead have a secret service host name. It looks from the proxy_pass that there's no API's except "/"?