Fix #485 test build of dev environment
radiasoft/rsconf pull request #486
Opened 2024-04-29 17:22 UTC by robnagler

2024-04-29 21:18 UTC, e-carlin requested changes

2024-04-29 23:35 UTC, robnagler commented on tests/pkcli/build_test.py
> +        raise
bad merge 2154fce

2024-04-30 20:58 UTC, robnagler commented
@e-carlin I think this is ready to go. Would prefer to merge before dkim changes

2024-04-30 23:26 UTC, e-carlin approved these changes

2024-04-30 23:28 UTC, e-carlin commented
lgtm. you merge

2024-04-30 23:44 UTC, merged